Repository jenkinsci/uipath-automation-package-plugin, pull requests merged in 2022-09, with the labels that each got.

#116 Localization sync from the Forked UiPath to Jenkins repo for Jenkins plugin #115 | Release/v2.10
  src/main/resources/com/uipath/uipathpackage/Messages_de.properties
  src/main/resources/com/uipath/uipathpackage/Messages_es-MX.properties
  src/main/resources/com/uipath/uipathpackage/Messages_es.properties
  src/main/resources/com/uipath/uipathpackage/Messages_fr.properties
  src/main/resources/com/uipath/uipathpackage/Messages_ja.properties
  src/main/resources/com/uipath/uipathpackage/Messages_ko.properties
  src/main/resources/com/uipath/uipathpackage/Messages_pt-BR.properties
  src/main/resources/com/uipath/uipathpackage/Messages_pt.properties
  src/main/resources/com/uipath/uipathpackage/Messages_ru.properties
  src/main/resources/com/uipath/uipathpackage/Messages_tr.properties
  src/main/resources/com/uipath/uipathpackage/Messages_zh-CN.properties
  src/main/resources/com/uipath/uipathpackage/config_de.properties
  src/main/resources/com/uipath/uipathpackage/config_es-MX.properties
  src/main/resources/com/uipath/uipathpackage/config_es.properties
  src/main/resources/com/uipath/uipathpackage/config_fr.properties
  src/main/resources/com/uipath/uipathpackage/config_ja.properties
  src/main/resources/com/uipath/uipathpackage/config_ko.properties
  src/main/resources/com/uipath/uipathpackage/config_pt-BR.properties
  src/main/resources/com/uipath/uipathpackage/config_pt.properties
  src/main/resources/com/uipath/uipathpackage/config_ru.properties
  src/main/resources/com/uipath/uipathpackage/config_tr.properties
  src/main/resources/com/uipath/uipathpackage/config_zh-CN.properties
  src/main/resources/com/uipath/uipathpackage/help_de.properties
  src/main/resources/com/uipath/uipathpackage/help_es-MX.properties
  src/main/resources/com/uipath/uipathpackage/help_es.properties
  src/main/resources/com/uipath/uipathpackage/help_fr.properties
  src/main/resources/com/uipath/uipathpackage/help_ja.properties
  src/main/resources/com/uipath/uipathpackage/help_ko.properties
  src/main/resources/com/uipath/uipathpackage/help_pt-BR.properties
  src/main/resources/com/uipath/uipathpackage/help_pt.properties
  src/main/resources/com/uipath/uipathpackage/help_ru.properties
  src/main/resources/com/uipath/uipathpackage/help_tr.properties
  src/main/resources/com/uipath/uipathpackage/help_zh-CN.properties
Labels: Localization

#115 Localization sync from the Forked UiPath to Jenkins repo for Jenkins plugin
  src/main/resources/com/uipath/uipathpackage/Messages_de.properties
  src/main/resources/com/uipath/uipathpackage/Messages_zh-CN.properties
  src/main/resources/com/uipath/uipathpackage/help_de.properties
  src/main/resources/com/uipath/uipathpackage/help_zh-CN.properties
Labels: Localization

#117 Updating the CLI version
  src/main/resources/config.properties
Labels: enhancement

#106 Release v2.10
  azure-pipelines.yml
  job.ci.build.yml
  src/main/java/com/uipath/uipathpackage/UiPathDeploy.java
  src/main/java/com/uipath/uipathpackage/models/AssetsOptions.java
  src/main/java/com/uipath/uipathpackage/models/DeployOptions.java
  src/main/java/com/uipath/uipathpackage/models/JobOptions.java
  src/main/java/com/uipath/uipathpackage/models/PackOptions.java
  src/main/java/com/uipath/uipathpackage/models/TestOptions.java
  src/main/resources/com/uipath/uipathpackage/Messages_es-MX.properties
  src/main/resources/com/uipath/uipathpackage/Messages_es.properties
  src/main/resources/com/uipath/uipathpackage/Messages_fr.properties
  src/main/resources/com/uipath/uipathpackage/Messages_ja.properties
  src/main/resources/com/uipath/uipathpackage/Messages_ko.properties
  src/main/resources/com/uipath/uipathpackage/Messages_pt-BR.properties
  src/main/resources/com/uipath/uipathpackage/Messages_pt.properties
  src/main/resources/com/uipath/uipathpackage/Messages_ru.properties
  src/main/resources/com/uipath/uipathpackage/Messages_tr.properties
  src/main/resources/com/uipath/uipathpackage/UiPathDeploy/config.jelly
  src/main/resources/com/uipath/uipathpackage/UiPathDeploy/config.properties
  src/main/resources/com/uipath/uipathpackage/config_es-MX.properties
  src/main/resources/com/uipath/uipathpackage/help.properties
  src/main/resources/com/uipath/uipathpackage/help_de.properties
  src/main/resources/com/uipath/uipathpackage/help_es-MX.properties
  src/main/resources/com/uipath/uipathpackage/help_es.properties
  src/main/resources/com/uipath/uipathpackage/help_fr.properties
  src/main/resources/com/uipath/uipathpackage/help_ja.properties
  src/main/resources/com/uipath/uipathpackage/help_ko.properties
  src/main/resources/com/uipath/uipathpackage/help_pt-BR.properties
  src/main/resources/com/uipath/uipathpackage/help_pt.properties
  src/main/resources/com/uipath/uipathpackage/help_ru.properties
  src/main/resources/com/uipath/uipathpackage/help_tr.properties
  src/main/resources/com/uipath/uipathpackage/help_zh-CN.properties
  src/main/resources/config.properties
  src/test/java/com/uipath/uipathpackage/UiPathDeployTests.java
  src/test/java/com/uipath/uipathpackage/UiPathTestTests.java
  stage.security.yml
Labels: bug, enhancement

#119 [SYNC MASTER] Release v2.10
  .vsts-ci-security.yml
  README.md
  azure-pipelines.yml
  job.ci.build.yml
  src/main/java/com/uipath/uipathpackage/UiPathDeploy.java
  src/main/java/com/uipath/uipathpackage/models/AssetsOptions.java
  src/main/java/com/uipath/uipathpackage/models/DeployOptions.java
  src/main/java/com/uipath/uipathpackage/models/JobOptions.java
  src/main/java/com/uipath/uipathpackage/models/PackOptions.java
  src/main/java/com/uipath/uipathpackage/models/TestOptions.java
  src/main/resources/com/uipath/uipathpackage/Messages_de.properties
  src/main/resources/com/uipath/uipathpackage/Messages_es-MX.properties
  src/main/resources/com/uipath/uipathpackage/Messages_es.properties
  src/main/resources/com/uipath/uipathpackage/Messages_fr.properties
  src/main/resources/com/uipath/uipathpackage/Messages_ja.properties
  src/main/resources/com/uipath/uipathpackage/Messages_ko.properties
  src/main/resources/com/uipath/uipathpackage/Messages_pt-BR.properties
  src/main/resources/com/uipath/uipathpackage/Messages_pt.properties
  src/main/resources/com/uipath/uipathpackage/Messages_ru.properties
  src/main/resources/com/uipath/uipathpackage/Messages_tr.properties
  src/main/resources/com/uipath/uipathpackage/Messages_zh-CN.properties
  src/main/resources/com/uipath/uipathpackage/UiPathDeploy/config.jelly
  src/main/resources/com/uipath/uipathpackage/UiPathDeploy/config.properties
  src/main/resources/com/uipath/uipathpackage/config_de.properties
  src/main/resources/com/uipath/uipathpackage/config_es-MX.properties
  src/main/resources/com/uipath/uipathpackage/config_es.properties
  src/main/resources/com/uipath/uipathpackage/config_fr.properties
  src/main/resources/com/uipath/uipathpackage/config_ja.properties
  src/main/resources/com/uipath/uipathpackage/config_ko.properties
  src/main/resources/com/uipath/uipathpackage/config_pt-BR.properties
  src/main/resources/com/uipath/uipathpackage/config_pt.properties
  src/main/resources/com/uipath/uipathpackage/config_ru.properties
  src/main/resources/com/uipath/uipathpackage/config_tr.properties
  src/main/resources/com/uipath/uipathpackage/config_zh-CN.properties
  src/main/resources/com/uipath/uipathpackage/help.properties
  src/main/resources/com/uipath/uipathpackage/help_de.properties
  src/main/resources/com/uipath/uipathpackage/help_es-MX.properties
  src/main/resources/com/uipath/uipathpackage/help_es.properties
  src/main/resources/com/uipath/uipathpackage/help_fr.properties
  src/main/resources/com/uipath/uipathpackage/help_ja.properties
  src/main/resources/com/uipath/uipathpackage/help_ko.properties
  src/main/resources/com/uipath/uipathpackage/help_pt-BR.properties
  src/main/resources/com/uipath/uipathpackage/help_pt.properties
  src/main/resources/com/uipath/uipathpackage/help_ru.properties
  src/main/resources/com/uipath/uipathpackage/help_tr.properties
  src/main/resources/com/uipath/uipathpackage/help_zh-CN.properties
  src/main/resources/config.properties
  src/test/java/com/uipath/uipathpackage/UiPathDeployTests.java
  src/test/java/com/uipath/uipathpackage/UiPathTestTests.java
  stage.security.yml
  stage.test.template.yml
Labels: enhancement

#123 Localization sync from the Forked UiPath to Jenkins repo for Jenkins plugin Localization
  src/main/resources/com/uipath/uipathpackage/Messages_es-MX.properties
  src/main/resources/com/uipath/uipathpackage/Messages_es.properties
  src/main/resources/com/uipath/uipathpackage/Messages_fr.properties
  src/main/resources/com/uipath/uipathpackage/Messages_ja.properties
  src/main/resources/com/uipath/uipathpackage/Messages_ko.properties
  src/main/resources/com/uipath/uipathpackage/Messages_pt-BR.properties
  src/main/resources/com/uipath/uipathpackage/Messages_pt.properties
  src/main/resources/com/uipath/uipathpackage/Messages_ru.properties
  src/main/resources/com/uipath/uipathpackage/Messages_tr.properties
  src/main/resources/com/uipath/uipathpackage/config_es-MX.properties
  src/main/resources/com/uipath/uipathpackage/help_de.properties
  src/main/resources/com/uipath/uipathpackage/help_es-MX.properties
  src/main/resources/com/uipath/uipathpackage/help_es.properties
  src/main/resources/com/uipath/uipathpackage/help_fr.properties
  src/main/resources/com/uipath/uipathpackage/help_ja.properties
  src/main/resources/com/uipath/uipathpackage/help_ko.properties
  src/main/resources/com/uipath/uipathpackage/help_pt-BR.properties
  src/main/resources/com/uipath/uipathpackage/help_pt.properties
  src/main/resources/com/uipath/uipathpackage/help_ru.properties
  src/main/resources/com/uipath/uipathpackage/help_tr.properties
  src/main/resources/com/uipath/uipathpackage/help_zh-CN.properties
Labels: Localization

#124 Localization sync from the Forked UiPath to Jenkins repo for Jenkins plugin Localization
  src/main/resources/com/uipath/uipathpackage/help_de.properties
  src/main/resources/com/uipath/uipathpackage/help_es-MX.properties
  src/main/resources/com/uipath/uipathpackage/help_es.properties
  src/main/resources/com/uipath/uipathpackage/help_fr.properties
  src/main/resources/com/uipath/uipathpackage/help_ja.properties
  src/main/resources/com/uipath/uipathpackage/help_ko.properties
  src/main/resources/com/uipath/uipathpackage/help_pt-BR.properties
  src/main/resources/com/uipath/uipathpackage/help_pt.properties
  src/main/resources/com/uipath/uipathpackage/help_ru.properties
  src/main/resources/com/uipath/uipathpackage/help_tr.properties
  src/main/resources/com/uipath/uipathpackage/help_zh-CN.properties
Labels: Localization
